// Waypoint timing stays synchronized with the approved flight baseline.
// Each stop declares its scene artwork plus an internal briefing sequence.
// The sequence changes only the information inside the arrival billboard.
export const waypoints = [
  {
    at: 0.04, title: 'Start here', color: '#cf6f2f', side: -0.20, lift: -0.02, visual: 'entry-vista',
    kicker: '01 / Mission premise',
    heading: 'AI gives me velocity. Experience gives it a bearing.',
    body: 'I learned engineering where a change leaves the screen and becomes hardware, configuration, cost, and consequence. I bring that same judgment into software built with AI.',
    proof: 'The advantage is not generating more. It is knowing what deserves to be built, what must not break, and what evidence proves the change worked.',
    action: 'See the hiring case', section: 'briefTitle',
    briefing: [
      {
        kicker: '01 / Mission premise',
        heading: 'AI gives me velocity. Experience gives it a bearing.',
        body: 'I learned engineering where a change leaves the screen and becomes hardware, configuration, cost, and consequence. I bring that same judgment into software built with AI.',
        proof: 'Speed matters only when it is pointed at the right problem.',
        visual: { type: 'trace', items: [
          { title: 'Problem', detail: 'Find the real friction' },
          { title: 'Boundary', detail: 'Protect what already works' },
          { title: 'Build', detail: 'Use AI for velocity' },
          { title: 'Evidence', detail: 'Prove the result' },
        ] },
      },
      {
        kicker: '01 / Operating context',
        heading: 'I have spent years where interfaces matter.',
        body: 'Mechanical design taught me that no part exists alone. CAD, PLM, manufacturing, revisions, and the person doing the work all meet at the interfaces.',
        proof: 'That is where I look first when a system fails: the handoff between what one part assumes and what the next part actually receives.',
        visual: { type: 'readout', items: [
          { value: '15+ years', label: 'Mechanical design' },
          { value: 'NX', label: 'Complex CAD systems' },
          { value: 'Teamcenter', label: 'Configuration and PLM' },
        ] },
      },
      {
        kicker: '01 / Development doctrine',
        heading: 'Build fast. Verify against the mission.',
        body: 'AI can collapse the distance between an idea and an implementation. I keep ownership of the architecture, constraints, diagnostics, and the condition that makes the result trustworthy.',
        proof: 'I want the actual failure surfaced, the next boundary named, and the useful work preserved for the next pass.',
        visual: { type: 'trace', items: [
          { title: 'Intent', detail: 'What must change' },
          { title: 'Constraint', detail: 'What must remain true' },
          { title: 'Diagnostic', detail: 'What actually happened' },
          { title: 'Next move', detail: 'Advance from evidence' },
        ] },
      },
      {
        kicker: '01 / Hiring signal',
        heading: 'Bring me the problem nobody wants to inherit.',
        body: 'The tangled workflow, the brittle interface, the tool everyone works around. Those are the places where engineering judgment and AI acceleration compound instead of merely adding.',
        proof: 'I am most useful where the system is complicated, the consequences are real, and the answer still has to feel simple to the person using it.',
        visual: { type: 'matrix', items: [
          { title: 'Root cause', detail: 'Trace the failure to its boundary' },
          { title: 'Traceability', detail: 'Keep decisions attached to evidence' },
          { title: 'Operator clarity', detail: 'Make the next action obvious' },
        ] },
      },
    ],
  },
  {
    at: 0.18, title: 'Engineering', color: '#66713f', side: 0.66, lift: -0.16, visual: 'engineering-assembly',
    kicker: '02 / Engineering foundations',
    heading: 'Every line on a drawing eventually meets the real world.',
    body: 'More than 15 years in mechanical design trained me to think beyond the model: fit, manufacturing, revisions, configuration, and downstream consequences.',
    proof: 'That discipline followed me from NX assemblies into Teamcenter administration and now into software.',
    action: 'Follow the engineering thread', section: 'engineering',
    briefing: [
      {
        kicker: '02 / Engineering foundations',
        heading: 'Every line on a drawing eventually meets the real world.',
        body: 'More than 15 years in mechanical design trained me to think beyond the model: fit, manufacturing, revisions, configuration, and downstream consequences.',
        proof: 'A design is not finished when it looks correct. It is finished when the system around it can carry the decision safely forward.',
        visual: { type: 'trace', items: [
          { title: 'Design', detail: 'Intent' },
          { title: 'Release', detail: 'Configuration' },
          { title: 'Build', detail: 'Manufacturing' },
          { title: 'Field', detail: 'Consequence' },
        ] },
      },
      {
        kicker: '02 / Configuration discipline',
        heading: 'A revision is never just a revision.',
        body: 'Change moves through assemblies, drawings, data, people, and process. My instinct is to ask what depends on this, who consumes it next, and how we know the right version survived the handoff.',
        proof: 'That habit is configuration management in practice, not as paperwork but as protection against invisible drift.',
        visual: { type: 'readout', items: [
          { value: 'Fit', label: 'Geometry must agree' },
          { value: 'Revision', label: 'Intent must remain traceable' },
          { value: 'Handoff', label: 'The next system must receive it intact' },
        ] },
      },
      {
        kicker: '02 / Systems view',
        heading: 'I learned to see the handoffs, not only the parts.',
        body: 'Solving difficult NX model and assembly problems led me into Teamcenter administration. The work moved from repairing one model to understanding the system that allowed an entire team to keep moving.',
        proof: 'I can speak from both sides of the interface: the person doing the engineering and the system expected to support them.',
        visual: { type: 'trace', items: [
          { title: 'Designer', detail: 'Needs flow' },
          { title: 'CAD', detail: 'Carries geometry' },
          { title: 'PLM', detail: 'Carries configuration' },
          { title: 'Team', detail: 'Carries the mission forward' },
        ] },
      },
      {
        kicker: '02 / Transfer to software',
        heading: 'Software deserves the same respect as hardware.',
        body: 'Define the interfaces. Protect known good behavior. Make failures inspectable. Leave the configuration understandable enough that another person can continue without reconstructing the past.',
        proof: 'Different medium, same engineering responsibility.',
        visual: { type: 'matrix', items: [
          { title: 'Boundaries', detail: 'Explicit interfaces' },
          { title: 'Verification', detail: 'Evidence before confidence' },
          { title: 'Continuity', detail: 'Work the next person can inherit' },
        ] },
      },
    ],
  },
  {
    at: 0.34, title: 'Vault automation', color: '#4c6378', side: -0.68, lift: 0.10, visual: 'automation-stack',
    kicker: '03 / Vault PDF History Export',
    heading: 'Repetition is a signal from the system.',
    body: 'When engineers repeatedly search drawings, revisions, and change records to reconstruct the same history, the workflow is asking to be redesigned.',
    proof: 'My Vault tool turns that scattered search into one reviewable path.',
    action: 'Read the automation case study', section: 'automation',
    briefing: [
      {
        kicker: '03 / Workflow automation',
        heading: 'Repetition is a signal from the system.',
        body: 'When engineers repeatedly search drawings, revisions, and change records to reconstruct the same history, the workflow is asking to be redesigned.',
        proof: 'Automation begins by recognizing where human attention is being spent on retrieval instead of judgment.',
        visual: { type: 'trace', items: [
          { title: 'Search', detail: 'Find the record' },
          { title: 'Rebuild', detail: 'Reconstruct history' },
          { title: 'Review', detail: 'Understand the change' },
          { title: 'Decide', detail: 'Use engineering judgment' },
        ] },
      },
      {
        kicker: '03 / Operational picture',
        heading: 'History should assemble itself before the reviewer arrives.',
        body: 'The tool brings drawing history, revision context, and change records into a connected review flow so the evidence is already organized when the person has to make a decision.',
        proof: 'The goal is not fewer records. It is less searching between them.',
        visual: { type: 'readout', items: [
          { value: 'Operations', label: 'Run the workflow' },
          { value: 'Documentation', label: 'Keep the method close' },
          { value: 'Metrics', label: 'See what the process is producing' },
        ] },
      },
      {
        kicker: '03 / Maintainability',
        heading: 'A tool should explain its own wiring.',
        body: 'I added a code map that connects visible features to their implementation. The application is not only meant to complete today’s task. It is meant to remain understandable when the next change arrives.',
        proof: 'Maintainability is part of the operator experience because opaque tools eventually become operational friction.',
        visual: { type: 'trace', items: [
          { title: 'Feature', detail: 'What the user sees' },
          { title: 'Code map', detail: 'Where it lives' },
          { title: 'Implementation', detail: 'How it works' },
          { title: 'Change', detail: 'Where to act next' },
        ] },
      },
      {
        kicker: '03 / Outcome',
        heading: 'The best automation leaves more room for judgment.',
        body: 'Good tooling removes the mechanical search, preserves the evidence, and gives the reviewer a clean path through the information without hiding the underlying record.',
        proof: 'Less hunting. Better context. A clearer decision surface.',
        visual: { type: 'matrix', items: [
          { title: 'Retrieve', detail: 'Bring the evidence together' },
          { title: 'Trace', detail: 'Keep history connected' },
          { title: 'Review', detail: 'Spend attention where it matters' },
        ] },
      },
    ],
  },
  {
    at: 0.51, title: 'ContextPort', color: '#694f66', side: 0.62, lift: -0.05, visual: 'context-port',
    kicker: '04 / ContextPort · Public source',
    heading: 'Memory is part of the system boundary.',
    body: 'I built ContextPort around a simple problem: changing AI providers should not mean abandoning the decisions and project history that made the work coherent.',
    proof: 'Context becomes a portable, revisioned record instead of something trapped inside one conversation.',
    action: 'Explore the product decisions', section: 'contextport',
    briefing: [
      {
        kicker: '04 / Context continuity',
        heading: 'Memory is part of the system boundary.',
        body: 'I built ContextPort around a simple problem: changing AI providers should not mean abandoning the decisions and project history that made the work coherent.',
        proof: 'If context carries the reasoning behind the work, preserving it is an engineering responsibility.',
        visual: { type: 'trace', items: [
          { title: 'Decision', detail: 'What changed' },
          { title: 'Memory', detail: 'Why it changed' },
          { title: 'Revision', detail: 'What came next' },
          { title: 'Provider', detail: 'Where work continues' },
        ] },
      },
      {
        kicker: '04 / Provider isolation',
        heading: 'Carry the mission record, not the session noise.',
        body: 'ContextPort keeps provider sessions isolated while letting the user move deliberate, device local Memory between them. Portability is controlled rather than automatic.',
        proof: 'The user decides what crosses the boundary.',
        visual: { type: 'readout', items: [
          { value: 'Device local', label: 'Memory stays under user control' },
          { value: 'Revisioned', label: 'Changes remain inspectable' },
          { value: '5 providers', label: 'One context can support multiple tools' },
        ] },
      },
      {
        kicker: '04 / Integrity',
        heading: 'Portability without provenance is just copying.',
        body: 'Conversation capture checks for evidence of message roles and rejects unsafe captures when a provider interface changes. The transfer path has to know when it no longer understands what it is reading.',
        proof: 'Fail closed when the evidence is ambiguous. Preserve context only when its structure is trustworthy.',
        visual: { type: 'trace', items: [
          { title: 'Capture', detail: 'Observe structure' },
          { title: 'Validate', detail: 'Confirm message roles' },
          { title: 'Reject', detail: 'Stop unsafe ambiguity' },
          { title: 'Carry', detail: 'Move trusted context' },
        ] },
      },
      {
        kicker: '04 / Product principle',
        heading: 'Context should move deliberately.',
        body: 'The product is not a pipe between chat windows. It is a controlled handoff of useful project memory, with export, revision history, and provider isolation built around that responsibility.',
        proof: 'Continuity without surrendering control.',
        visual: { type: 'matrix', items: [
          { title: 'Portable', detail: 'Move useful history' },
          { title: 'Inspectable', detail: 'See revisions and exports' },
          { title: 'Isolated', detail: 'Keep provider sessions separate' },
        ] },
      },
    ],
  },
  {
    at: 0.69, title: 'ipaSim', color: '#96543f', side: -0.62, lift: 0.14, visual: 'runtime-bridge',
    kicker: '05 / ipaSim · Active open-source fork',
    heading: 'When the map says the road ends, inspect the boundary.',
    body: 'Compatibility work becomes useful when the failure is reduced to the exact interface that does not translate. That is where I focus the next change.',
    proof: 'Progress is a narrower unknown backed by a real diagnostic.',
    action: 'Inspect the runtime case study', section: 'ipasim',
    briefing: [
      {
        kicker: '05 / Runtime engineering',
        heading: 'When the map says the road ends, inspect the boundary.',
        body: 'Compatibility work becomes useful when the failure is reduced to the exact interface that does not translate. That is where I focus the next change.',
        proof: 'A precise failure is not a setback. It is a coordinate.',
        visual: { type: 'trace', items: [
          { title: 'Observe', detail: 'Capture the real failure' },
          { title: 'Reduce', detail: 'Find the boundary' },
          { title: 'Change', detail: 'Repair the architecture' },
          { title: 'Advance', detail: 'Expose the next truth' },
        ] },
      },
      {
        kicker: '05 / Architecture',
        heading: 'Stop rebuilding the terrain. Read it where it lives.',
        body: 'When Windows could not reproduce the runtime filesystem cleanly, the useful direction was architectural: read the immutable image directly instead of repeatedly extracting the same world into a different one.',
        proof: 'Change the boundary causing the mismatch, not the symptoms surrounding it.',
        visual: { type: 'trace', items: [
          { title: 'Runtime image', detail: 'Source of truth' },
          { title: 'Reader', detail: 'Direct access' },
          { title: 'Loader', detail: 'Consume real frameworks' },
          { title: 'Guest', detail: 'Continue execution' },
        ] },
      },
      {
        kicker: '05 / Evidence',
        heading: 'A real failure is more valuable than a false green.',
        body: 'Merged PR #78 demonstrates the Windows loader reading real frameworks from a complete DwarFS runtime image without mounting or extracting it.',
        proof: 'The probe then reaches a documented unresolved import. The storage milestone is real, and the next compatibility boundary is visible.',
        visual: { type: 'readout', items: [
          { value: 'PR #78', label: 'Merged implementation' },
          { value: 'DwarFS', label: 'Runtime read directly' },
          { value: 'Next import', label: 'Failure remains explicit' },
        ] },
      },
      {
        kicker: '05 / Next boundary',
        heading: 'Advance until the next honest obstacle appears.',
        body: 'I use AI to accelerate the implementation loop, but the loop is governed by evidence: preserve working ground, expose the diagnostic, and make the next unresolved boundary smaller than the last.',
        proof: 'That is how a difficult compatibility problem becomes a sequence of finishable engineering decisions.',
        visual: { type: 'matrix', items: [
          { title: 'Preserve', detail: 'Keep known good work' },
          { title: 'Expose', detail: 'Surface the actual failure' },
          { title: 'Advance', detail: 'Solve one boundary at a time' },
        ] },
      },
    ],
  },
  {
    at: 0.85, title: 'Clarity', color: '#a9792f', side: 0.68, lift: 0.05, visual: 'clarity-map',
    kicker: '06 / Information people can use',
    heading: 'Complexity should arrive as an instrument panel, not a fog bank.',
    body: 'Maps, records, coverage, diagnostics, and source references only matter when they help a person understand the situation and make the next decision.',
    proof: 'Clarity is not decoration. It is part of system performance.',
    action: 'See how I think and present', section: 'clarity',
    briefing: [
      {
        kicker: '06 / Decision support',
        heading: 'Complexity should arrive as an instrument panel, not a fog bank.',
        body: 'Maps, records, coverage, diagnostics, and source references only matter when they help a person understand the situation and make the next decision.',
        proof: 'Clarity is not decoration. It is part of system performance.',
        visual: { type: 'trace', items: [
          { title: 'Situation', detail: 'What is happening' },
          { title: 'Evidence', detail: 'Why we believe it' },
          { title: 'Decision', detail: 'What it means' },
          { title: 'Action', detail: 'What happens next' },
        ] },
      },
      {
        kicker: '06 / Information architecture',
        heading: 'Show what matters now, and where the evidence lives.',
        body: 'I design the path from the operational picture down to the record that supports it. The overview and the source should never become two disconnected worlds.',
        proof: 'A person should be able to move from understanding to inspection without losing the thread.',
        visual: { type: 'readout', items: [
          { value: 'Overview', label: 'See the whole system' },
          { value: 'Source', label: 'Inspect the underlying record' },
          { value: 'Action', label: 'Know what to do next' },
        ] },
      },
      {
        kicker: '06 / Diagnostics',
        heading: 'A failure should point forward.',
        body: 'I want the useful diagnostic where the team can see it, attached to the thing that failed, with enough context to identify the next actionable problem without digging through noise.',
        proof: 'Failure becomes useful when it reduces uncertainty.',
        visual: { type: 'trace', items: [
          { title: 'Failure', detail: 'What broke' },
          { title: 'Diagnostic', detail: 'What the system observed' },
          { title: 'Boundary', detail: 'Where to investigate' },
          { title: 'Action', detail: 'What to fix next' },
        ] },
      },
      {
        kicker: '06 / Design doctrine',
        heading: 'After many notes, simplicity emerges as a crowning art.',
        body: 'That is the standard I keep returning to. The hard work can remain complex underneath, but the person using the result should meet a system that is legible, deliberate, and calm.',
        proof: 'Make complexity understandable without pretending it disappeared.',
        visual: { type: 'matrix', items: [
          { title: 'Readable', detail: 'The system explains itself' },
          { title: 'Traceable', detail: 'Evidence stays connected' },
          { title: 'Usable', detail: 'The next action feels obvious' },
        ] },
      },
    ],
  },
];
